@ stdcall -stub AddPersonalTrustDBPages(ptr ptr ptr)
@ stdcall -stub CatalogCompactHashDatabase(wstr wstr wstr wstr)
#@ stub ComputeFirstPageHash
#@ stub ConfigCiFinalPolicy
#@ stub ConfigCiPackageFamilyNameCheck
@ stdcall CryptCATAdminAcquireContext(ptr ptr long)
@ stdcall CryptCATAdminAcquireContext2(ptr ptr wstr ptr long)
@ stdcall CryptCATAdminAddCatalog(long wstr wstr long)
@ stdcall CryptCATAdminCalcHashFromFileHandle(long ptr ptr long)
@ stdcall -stub CryptCATAdminCalcHashFromFileHandle2(ptr ptr ptr ptr long)
@ stdcall CryptCATAdminEnumCatalogFromHash(long ptr long long ptr)
@ stdcall -stub CryptCATAdminPauseServiceForBackup(long long)
@ stdcall CryptCATAdminReleaseCatalogContext(long long long)
@ stdcall CryptCATAdminReleaseContext(long long)
@ stdcall CryptCATAdminRemoveCatalog(ptr wstr long)
@ stdcall CryptCATAdminResolveCatalogPath(ptr wstr ptr long)
@ stdcall -stub CryptCATAllocSortedMemberInfo(ptr wstr)
@ stdcall CryptCATCDFClose(ptr)
@ stdcall -stub CryptCATCDFEnumAttributes(ptr ptr ptr ptr)
@ stdcall -stub CryptCATCDFEnumAttributesWithCDFTag(ptr wstr ptr ptr ptr)
@ stdcall CryptCATCDFEnumCatAttributes(ptr ptr ptr)
@ stdcall -stub CryptCATCDFEnumMembers(ptr ptr ptr)
@ stdcall -stub CryptCATCDFEnumMembersByCDFTag(ptr wstr ptr ptr)
@ stdcall CryptCATCDFEnumMembersByCDFTagEx(ptr wstr ptr ptr long ptr)
@ stdcall CryptCATCDFOpen(wstr ptr)
@ stdcall CryptCATCatalogInfoFromContext(ptr ptr long)
@ stdcall CryptCATClose(long)
@ stdcall CryptCATEnumerateAttr(ptr ptr ptr)
@ stdcall CryptCATEnumerateCatAttr(ptr ptr)
@ stdcall CryptCATEnumerateMember(long ptr)
@ stdcall -stub CryptCATFreeSortedMemberInfo(ptr ptr)
@ stdcall CryptCATGetAttrInfo(ptr ptr wstr)
@ stdcall CryptCATGetCatAttrInfo(ptr wstr )
@ stdcall CryptCATGetMemberInfo(ptr wstr)
@ stdcall -stub CryptCATHandleFromStore(ptr)
@ stdcall CryptCATOpen(wstr long long long long)
@ stdcall -stub CryptCATPersistStore(ptr)
@ stdcall -stub CryptCATPutAttrInfo(ptr ptr wstr long long ptr)
@ stdcall -stub CryptCATPutCatAttrInfo(ptr wstr long long ptr)
@ stdcall -stub CryptCATPutMemberInfo(ptr wstr wstr ptr long long ptr)
@ stdcall -stub CryptCATStoreFromHandle(ptr)
@ stdcall -stub CryptCATVerifyMember(ptr ptr ptr)
@ stdcall CryptSIPCreateIndirectData(ptr ptr ptr)
@ stdcall -stub CryptSIPGetCaps(ptr ptr)
@ stdcall -stub CryptSIPGetInfo(ptr)
@ stdcall -stub CryptSIPGetRegWorkingFlags(ptr)
#@ stub CryptSIPGetSealedDigest
@ stdcall CryptSIPGetSignedDataMsg(ptr ptr long ptr ptr)
@ stdcall CryptSIPPutSignedDataMsg(ptr long ptr long ptr)
@ stdcall CryptSIPRemoveSignedDataMsg(ptr long)
@ stdcall CryptSIPVerifyIndirectData(ptr ptr)
@ stdcall DllRegisterServer()
@ stdcall DllUnregisterServer()
@ stdcall DriverCleanupPolicy(ptr)
@ stdcall DriverFinalPolicy(ptr)
@ stdcall DriverInitializePolicy(ptr)
@ stdcall FindCertsByIssuer(ptr ptr ptr ptr long wstr long)
@ stdcall GenericChainCertificateTrust(ptr)
@ stdcall GenericChainFinalProv(ptr)
#@ stub GetAuthenticodeSha256Hash
@ stdcall HTTPSCertificateTrust(ptr)
@ stdcall HTTPSFinalProv(ptr)
@ stdcall IsCatalogFile(ptr wstr)
@ stdcall -stub MsCatConstructHashTag(long ptr wstr)
@ stdcall -stub MsCatFreeHashTag(wstr)
@ stdcall -stub OfficeCleanupPolicy(ptr)
@ stdcall -stub OfficeInitializePolicy(ptr)
@ stdcall OpenPersonalTrustDBDialog(ptr)
#@ stub OpenPersonalTrustDBDialogEx
@ stdcall SoftpubAuthenticode(ptr)
@ stdcall SoftpubCheckCert(ptr long long long)
@ stdcall SoftpubCleanup(ptr)
@ stdcall SoftpubDefCertInit(ptr)
@ stdcall SoftpubDllRegisterServer()
@ stdcall SoftpubDllUnregisterServer()
@ stdcall -stub SoftpubDumpStructure(ptr)
@ stdcall -stub SoftpubFreeDefUsageCallData(str ptr)
@ stdcall SoftpubInitialize(ptr)
@ stdcall -stub SoftpubLoadDefUsageCallData(str ptr)
@ stdcall SoftpubLoadMessage(ptr)
@ stdcall SoftpubLoadSignature(ptr)
#@ stub SrpCheckSmartlockerEAandProcessToken
@ stdcall -stub TrustDecode(long ptr ptr long long str ptr long long)
@ stdcall -stub TrustFindIssuerCertificate(ptr long long ptr ptr ptr ptr )
@ stdcall -stub TrustFreeDecode(ptr long)
@ stdcall TrustIsCertificateSelfSigned(ptr)
@ stdcall -stub TrustOpenStores(ptr ptr ptr long)
#@ stub WTGetBioSignatureInfo
#@ stub WTGetPluginSignatureInfo
#@ stub WTGetSignatureInfo
@ stdcall WTHelperCertCheckValidSignature(ptr)
@ stdcall -stub WTHelperCertFindIssuerCertificate(ptr long ptr ptr long ptr ptr)
@ stdcall -stub WTHelperCertIsSelfSigned(long ptr)
@ stdcall -stub WTHelperCheckCertUsage(ptr str)
@ stdcall -stub WTHelperGetAgencyInfo(ptr ptr ptr)
@ stdcall WTHelperGetFileHandle(ptr)
@ stdcall -stub WTHelperGetFileHash(wstr long ptr ptr ptr ptr)
@ stdcall WTHelperGetFileName(ptr)
@ stdcall WTHelperGetKnownUsages(long ptr)
@ stdcall WTHelperGetProvCertFromChain(ptr long)
@ stdcall WTHelperGetProvPrivateDataFromChain(ptr ptr)
@ stdcall WTHelperGetProvSignerFromChain(ptr long long long)
#@ stub WTHelperIsChainedToMicrosoft
#@ stub WTHelperIsChainedToMicrosoftFromStateData
@ stdcall -stub WTHelperIsInRootStore(ptr ptr)
@ stdcall -stub WTHelperOpenKnownStores(ptr)
@ stdcall WTHelperProvDataFromStateData(ptr)
#@ stub WTIsFirstConfigCiResultPreferred
#@ stub WTLogConfigCiScriptEvent
#@ stub WTLogConfigCiSignerEvent
#@ stub WTValidateBioSignaturePolicy
@ stdcall -stub WVTAsn1CatMemberInfo2Decode(long long ptr long long ptr ptr)
@ stdcall -stub WVTAsn1CatMemberInfo2Encode(long long ptr ptr ptr)
@ stdcall WVTAsn1CatMemberInfoDecode(long str ptr long long ptr ptr)
@ stdcall WVTAsn1CatMemberInfoEncode(long str ptr ptr ptr)
@ stdcall WVTAsn1CatNameValueDecode(long str ptr long long ptr ptr)
@ stdcall WVTAsn1CatNameValueEncode(long str ptr ptr ptr)
#@ stub WVTAsn1IntentToSealAttributeDecode
#@ stub WVTAsn1IntentToSealAttributeEncode
#@ stub WVTAsn1SealingSignatureAttributeDecode
#@ stub WVTAsn1SealingSignatureAttributeEncode
#@ stub WVTAsn1SealingTimestampAttributeDecode
#@ stub WVTAsn1SealingTimestampAttributeEncode
@ stdcall WVTAsn1SpcFinancialCriteriaInfoDecode(long str ptr long long ptr ptr)
@ stdcall WVTAsn1SpcFinancialCriteriaInfoEncode(long str ptr ptr ptr)
@ stdcall WVTAsn1SpcIndirectDataContentDecode(long str ptr long long ptr ptr)
@ stdcall WVTAsn1SpcIndirectDataContentEncode(long str ptr ptr ptr)
@ stdcall WVTAsn1SpcLinkDecode(long str ptr long long ptr ptr)
@ stdcall WVTAsn1SpcLinkEncode(long str ptr ptr ptr)
@ stdcall -stub WVTAsn1SpcMinimalCriteriaInfoDecode(long str ptr long long  ptr ptr)
@ stdcall -stub WVTAsn1SpcMinimalCriteriaInfoEncode(long str ptr ptr ptr)
@ stdcall WVTAsn1SpcPeImageDataDecode(long str ptr long long ptr ptr)
@ stdcall WVTAsn1SpcPeImageDataEncode(long str ptr ptr ptr)
@ stdcall -stub WVTAsn1SpcSigInfoDecode(long str ptr long long ptr long)
@ stdcall -stub WVTAsn1SpcSigInfoEncode(long str ptr ptr long)
@ stdcall -stub WVTAsn1SpcSpAgencyInfoDecode(long str ptr long long ptr long)
@ stdcall -stub WVTAsn1SpcSpAgencyInfoEncode(long str ptr ptr ptr)
@ stdcall WVTAsn1SpcSpOpusInfoDecode(long str ptr long long ptr ptr)
@ stdcall WVTAsn1SpcSpOpusInfoEncode(long str ptr ptr ptr)
@ stdcall -stub WVTAsn1SpcStatementTypeDecode(long str ptr long long ptr ptr)
@ stdcall -stub WVTAsn1SpcStatementTypeEncode(long str ptr ptr ptr)
@ stdcall WinVerifyTrust(long ptr ptr)
@ stdcall WinVerifyTrustEx(long ptr ptr)
@ stdcall WintrustAddActionID(ptr long ptr)
@ stdcall WintrustAddDefaultForUsage(ptr ptr)
@ stdcall WintrustCertificateTrust(ptr)
@ stdcall -stub WintrustGetDefaultForUsage(long str ptr)
@ stdcall WintrustGetRegPolicyFlags(ptr)
@ stdcall WintrustLoadFunctionPointers(ptr ptr)
@ stdcall WintrustRemoveActionID(ptr)
@ stdcall -stub WintrustSetDefaultIncludePEPageHashes(long)
@ stdcall WintrustSetRegPolicyFlags(long)
@ stdcall mscat32DllRegisterServer()
@ stdcall mscat32DllUnregisterServer()
@ stdcall mssip32DllRegisterServer()
@ stdcall mssip32DllUnregisterServer()
