@ stdcall HttpAddFragmentToCache(ptr wstr ptr ptr ptr)
@ stdcall HttpAddUrl(ptr wstr ptr)
#@ stdcall HttpAddUrlToConfigGroup(ptr ptr wstr ptr)
#@ stdcall HttpCreateAppPool(ptr wstr ptr long)
#@ stdcall HttpCreateConfigGroup(ptr ptr)
#@ stdcall HttpCreateFilter(ptr wstr ptr long)
@ stdcall HttpCreateHttpHandle(ptr long)
#@ stdcall HttpDeleteConfigGroup(ptr long)
@ stdcall HttpDeleteServiceConfiguration(ptr long ptr long ptr)
#@ stdcall HttpFilterAccept(ptr ptr long ptr ptr)
#@ stdcall HttpFilterAppRead(ptr int64 ptr long ptr ptr)
#@ stdcall HttpFilterAppWrite(ptr int64 ptr long ptr ptr)
#@ stdcall HttpFilterAppWriteAndRawRead(ptr ptr ptr)
#@ stdcall HttpFilterClose(ptr int64 ptr)
#@ stdcall HttpFilterRawRead(ptr int64 ptr long ptr ptr)
#@ stdcall HttpFilterRawWrite(ptr int64 ptr long ptr ptr)
#@ stdcall HttpFilterRawWriteAndAppRead(ptr ptr ptr)
@ stdcall HttpFlushResponseCache(ptr wstr long ptr)
@ stdcall HttpGetCounters(ptr long ptr ptr ptr)
@ stdcall HttpInitialize(long long ptr)
#@ stdcall HttpOpenAppPool(ptr wstr long)
#@ stdcall HttpOpenControlChannel(ptr long)
#@ stdcall HttpOpenFilter(ptr wstr long)
#@ stdcall HttpQueryAppPoolInformation(ptr long ptr long ptr)
#@ stdcall HttpQueryConfigGroupInformation(ptr ptr long ptr long ptr)
#@ stdcall HttpQueryControlChannelInformation(ptr long ptr long ptr)
@ stdcall HttpQueryServiceConfiguration(ptr long ptr long ptr long ptr ptr)
@ stdcall HttpReadFragmentFromCache(ptr wstr ptr ptr long ptr ptr)
@ stdcall HttpReceiveClientCertificate(ptr ptr long ptr long ptr ptr)
@ stdcall HttpReceiveHttpRequest(ptr int64 long ptr long ptr ptr)
@ stdcall HttpReceiveRequestEntityBody(ptr int64 long ptr long ptr ptr)
#@ stdcall HttpRemoveAllUrlsFromConfigGroup(ptr ptr)
@ stdcall HttpRemoveUrl(ptr wstr)
#@ stdcall HttpRemoveUrlFromConfigGroup(ptr ptr wstr)
@ stdcall HttpSendHttpResponse(ptr int64 long ptr ptr ptr ptr long ptr ptr)
@ stdcall HttpSendResponseEntityBody(ptr ptr long long ptr ptr ptr long ptr ptr)
#@ stdcall HttpSetAppPoolInformation(ptr long ptr long)
#@ stdcall HttpSetConfigGroupInformation(ptr ptr long ptr long)
#@ stdcall HttpSetControlChannelInformation(ptr long ptr long)
@ stdcall HttpSetServiceConfiguration(ptr long ptr long ptr)
#@ stdcall HttpShutdownAppPool(ptr)
#@ stdcall HttpShutdownFilter(ptr)
@ stdcall HttpTerminate(long ptr)
@ stdcall HttpWaitForDemandStart(ptr ptr long ptr ptr)
@ stdcall HttpWaitForDisconnect(ptr ptr ptr)


#Vista functions
@ stdcall HttpAddUrlToUrlGroup(int64 wstr int64 long)
@ stdcall HttpCreateRequestQueue(long wstr ptr long ptr)
@ stdcall HttpCreateServerSession(long ptr long)
@ stdcall HttpCreateUrlGroup(int64 ptr long)
@ stdcall HttpRemoveUrlFromUrlGroup(int64 wstr long)
@ stdcall HttpSetUrlGroupProperty(int64 long ptr long)
@ stdcall HttpShutdownRequestQueue(ptr)
;@ stdcall HttpWaitForDisconnect(ptr ptr long ptr)