@ stdcall -stub HttpAddFragmentToCache(ptr wstr ptr ptr ptr)
@ stdcall -stub HttpAddUrl(ptr wstr ptr)
@ stdcall -stub HttpAddUrlToConfigGroup(ptr ptr wstr ptr)
@ stdcall -stub HttpAddUrlToUrlGroup(int64 wstr int64 long)
@ stdcall -stub HttpCreateAppPool(ptr wstr ptr long)
@ stdcall -stub HttpCreateConfigGroup(ptr ptr)
@ stdcall -stub HttpCreateFilter(ptr wstr ptr long)
@ stdcall -stub HttpCreateHttpHandle(ptr long)
@ stdcall -stub HttpDeleteConfigGroup(ptr long)
@ stdcall -stub HttpDeleteServiceConfiguration(ptr long ptr long ptr)
@ stdcall -stub HttpFilterAccept(ptr ptr long ptr ptr)
@ stdcall -stub HttpFilterAppRead(ptr int64 ptr long ptr ptr)
@ stdcall -stub HttpFilterAppWrite(ptr int64 ptr long ptr ptr)
@ stdcall -stub HttpFilterAppWriteAndRawRead(ptr ptr ptr)
@ stdcall -stub HttpFilterClose(ptr int64 ptr)
@ stdcall -stub HttpFilterRawRead(ptr int64 ptr long ptr ptr)
@ stdcall -stub HttpFilterRawWrite(ptr int64 ptr long ptr ptr)
@ stdcall -stub HttpFilterRawWriteAndAppRead(ptr ptr ptr)
@ stdcall -stub HttpFlushResponseCache(ptr wstr long ptr)
@ stdcall -stub HttpGetCounters(ptr long ptr ptr ptr)
@ stdcall -stub HttpInitialize(long long ptr)
@ stdcall -stub HttpOpenAppPool(ptr wstr long)
@ stdcall -stub HttpOpenControlChannel(ptr long)
@ stdcall -stub HttpOpenFilter(ptr wstr long)
@ stdcall -stub HttpQueryAppPoolInformation(ptr long ptr long ptr)
@ stdcall -stub HttpQueryConfigGroupInformation(ptr ptr long ptr long ptr)
@ stdcall -stub HttpQueryControlChannelInformation(ptr long ptr long ptr)
@ stdcall -stub HttpQueryServiceConfiguration(ptr long ptr long ptr long ptr ptr)
@ stdcall -stub HttpReadFragmentFromCache(ptr wstr ptr ptr long ptr ptr)
@ stdcall -stub HttpReceiveClientCertificate(ptr ptr long ptr long ptr ptr)
@ stdcall -stub HttpReceiveHttpRequest(ptr int64 long ptr long ptr ptr)
@ stdcall -stub HttpReceiveRequestEntityBody(ptr int64 long ptr long ptr ptr)
@ stdcall -stub HttpRemoveAllUrlsFromConfigGroup(ptr ptr)
@ stdcall -stub HttpRemoveUrl(ptr wstr)
@ stdcall -stub HttpRemoveUrlFromConfigGroup(ptr ptr wstr)
@ stdcall -stub HttpRemoveUrlFromUrlGroup(int64 wstr long)
@ stdcall -stub HttpSendHttpResponse(ptr int64 long ptr ptr ptr ptr long ptr ptr)
@ stdcall -stub HttpSendResponseEntityBody(ptr ptr long long ptr ptr ptr long ptr ptr)
@ stdcall -stub HttpSetAppPoolInformation(ptr long ptr long)
@ stdcall -stub HttpSetConfigGroupInformation(ptr ptr long ptr long)
@ stdcall -stub HttpSetControlChannelInformation(ptr long ptr long)
@ stdcall -stub HttpSetServiceConfiguration(ptr long ptr long ptr)
@ stdcall -stub HttpShutdownAppPool(ptr)
@ stdcall -stub HttpShutdownFilter(ptr)
@ stdcall -stub HttpTerminate(long ptr)
@ stdcall -stub HttpWaitForDemandStart(ptr ptr long ptr ptr)
@ stdcall -stub HttpWaitForDisconnect(ptr ptr ptr)